datasource:
  url: mysql+pymysql://root:root@localhost:3306/fastapi
  maxPool: 100
  poolRecycle: 3600 #Recycle connections after 1 hour
  poolPrePing: True #Check connections before using them
  maxOverflow: 20 #Allow up to 20 extra connections beyond pool size
  poolTimeout: 30 #Wait up to 30 seconds for a connection from the pool


esewaUrl:
  esewaMF: http://10.13.194.23:7080
  customer: http://10.13.194.23:1080

resttemplate:
  default:
    connectTimeout: 30000
    socketTimeout: 30000
    maxPerRoute: 25
    maxTotalConnection: 100

